[workspace]
resolver = "2"
members = [
  "crates/rustyfi-syntax",
  "crates/rustyfi-backend",
  "crates/rustyfi-lang",
  "crates/rustyfi-pdf",
  "crates/rustyfi-html",
  "crates/rustyfi",
  "crates/rustyfi-loader",
  "crates/rustyfi-satyrographos",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Yasuo Ozu <yasuo@ozu.email>"]
repository = "https://github.com/yasuo-ozu/rustyfi"
homepage = "https://github.com/yasuo-ozu/rustyfi"
keywords = ["satysfi", "typesetting", "pdf", "typography"]
categories = ["text-processing", "command-line-utilities"]
readme = "README.md"

[workspace.dependencies]
syan = "0.2.0"
rustyfi-syntax = { path = "crates/rustyfi-syntax", version = "0.1.0" }
rustyfi-backend = { path = "crates/rustyfi-backend", version = "0.1.0" }
rustyfi-lang = { path = "crates/rustyfi-lang", version = "0.1.0" }
rustyfi-pdf = { path = "crates/rustyfi-pdf", version = "0.1.0" }
rustyfi-html = { path = "crates/rustyfi-html", version = "0.1.0" }
rustyfi-loader = { path = "crates/rustyfi-loader", version = "0.1.0" }
rustyfi-satyrographos = { path = "crates/rustyfi-satyrographos", version = "0.1.0" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tar = "0.4"
flate2 = "1"
sha2 = "0.10"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_mangen = "0.2"
pdf-writer = "0.13"
safegraph = "0.1"
ttf-parser = "0.25"
newer-type = "0.3"
newer-type-std = "0.3"
image = { version = "0.25", default-features = false, features = [
  "png",
  "jpeg",
] }
lopdf = "0.36"

#                            incremental    cold   target/debug
#   debug = 0                      10.3s     78s         3.1 GB
#   debug = "line-tables-only"     20.4s     78s         6.7 GB
#   debug = 1                      24.1s     78s         9.1 GB
#   debug = 2                      40.6s    119s          15 GB   <- cargo default
[profile.dev]
debug = 1
