{
  # Two things live here: rustyfi itself, and the ORIGINAL OCaml SATySFi that
  # the layout-fidelity harness and `benchmark.py` measure it against.
  #
  #   nix build                    # rustyfi
  #   nix run . -- doc.saty        # compile a document
  #   nix run .#satysfi -- --version
  #   nix develop                  # rust toolchain + satysfi + poppler + python3
  #
  # Nixpkgs ships SATySFi 0.0.11, a 0.0.x release matching the corpus's 0.0.x
  # documents, so the comparison target is pinned rather than dependent on
  # whatever a given machine happens to have.
  #
  # The dev shell also carries a TeX Live, for `--format latex`: a backend that
  # emits `.tex` is only as good as the last time someone compiled its output,
  # and "it looks like valid LaTeX" is not a test. See `texForRustyfi` below for
  # what is in it and why.

  description = "rustyfi — a native Rust port of the SATySFi typesetter";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    let
      # ── the package ────────────────────────────────────────────────────────
      #
      # The install layout is the one `install.sh` documents and the binary
      # depends on: it locates `lib/` and `share/` relative to its own path
      # (`roots.rs`'s `exe_prefix`, via `current_exe`, which resolves symlinks —
      # so a store path and a profile symlink both work).
      #
      #   bin/rustyfi
      #   lib/rustyfi/dist/packages/       0.0 packages
      #   lib/rustyfi/dist-v01/packages/   0.1 packages
      #   share/rustyfi/config.toml        shipped defaults, shadowed by ~/.config
      #   share/man/man1/rustyfi.1         generated by the binary itself
      #
      # NO FONTS. The faces `download-fonts.sh` fetches are gitignored, so they
      # are not in the flake source and cannot be — a fixed-output fetch would
      # belong in nixpkgs, not here. Without them text is set in the built-in
      # base-14 faces, which is enough for a plain document class (`stdja-mini`
      # renders) but not for `stdjabook`, whose own output contains an em-dash
      # that WinAnsi cannot encode, nor for anything CJK or math. Point
      # `programs.rustyfi.fontsDir` at a real font root for those.
      mkRustyfi = pkgs:
        pkgs.rustPlatform.buildRustPackage {
          pname = "rustyfi";
          version = "0.1.0";

          src = pkgs.lib.cleanSource ./.;
          cargoLock.lockFile = ./Cargo.lock;

          # The suite wants the vendored corpus, a font store and (for the
          # fidelity tests) poppler and python3. `nix flake check` runs the
          # library tests instead — see `checks` below.
          doCheck = false;

          postInstall = ''
            mkdir -p $out/lib/rustyfi $out/share/rustyfi \
                     $out/share/man/man1 $out/share/doc/rustyfi
            cp -R lib-rustyfi/dist lib-rustyfi/dist-v01 $out/lib/rustyfi/
            cp lib-rustyfi/LICENSE $out/lib/rustyfi/LICENSE
            cp config.toml $out/share/rustyfi/
            cp README.md LICENSE LICENSE.LGPL-3.0 LICENSE.GPL-3.0 \
               THIRD-PARTY-NOTICES.md $out/share/doc/rustyfi/

            # `dist/{fonts,hash}` carry a .gitignore that means nothing here.
            rm -f $out/lib/rustyfi/dist/fonts/.gitignore \
                  $out/lib/rustyfi/dist/hash/.gitignore

            # The man page is generated by the program, so it cannot drift from
            # the CLI it documents.
            $out/bin/rustyfi man > $out/share/man/man1/rustyfi.1
            test -s $out/share/man/man1/rustyfi.1
          '';

          meta = with pkgs.lib; {
            description = "A native Rust port of the SATySFi typesetter";
            longDescription = ''
              Compiles SATySFi documents (.saty) to PDF, supporting both the
              0.0.6 and 0.1 language generations, including cross-version
              imports. The Rust crates are MIT; the bundled lib-rustyfi corpus
              is upstream SATySFi's and stays LGPL-3.0 (see
              share/doc/rustyfi/THIRD-PARTY-NOTICES.md).
            '';
            homepage = "https://github.com/yasuo-ozu/rustyfi";
            license = licenses.mit;
            mainProgram = "rustyfi";
            platforms = platforms.unix;
          };
        };

      # ── the TeX Live the `--format latex` output needs ─────────────────────
      #
      # A curated set rather than `scheme-full`, which is ~7 GB for a handful of
      # packages, and rather than `scheme-small` alone, which has neither
      # `luatexja` nor `pgf` and so cannot typeset either of the two things this
      # backend most needs to prove: Japanese, and a drawing.
      #
      # `lualatex` rather than `pdflatex` is the intended engine, and the CJK
      # corpus is why. `pdflatex` cannot set Japanese at all; `xelatex` can with
      # `fontspec`, but `luatexja` is what upstream SATySFi's own audience uses
      # and it handles the JLreq line-breaking rules the port implements.
      # `pdflatex` stays available for Latin-only output.
      texForRustyfi = pkgs:
        pkgs.texliveSmall.withPackages (ps: with ps; [
          # Engines and the build driver. `scheme-small` already has xetex;
          # luatex and latexmk are the additions.
          latexmk
          luatex

          # Math. `amsmath` is the baseline; `unicode-math` is what lets a
          # Unicode-math engine set the same characters the port's own math
          # layout works in, rather than round-tripping them through 7-bit
          # macro names.
          amsmath
          amsfonts
          unicode-math
          mathtools
          lualatex-math  # unicode-math/mathtools pull this under lualatex

          # Fonts, and the Japanese support that needs them. `haranoaji` is the
          # open Japanese family; without it `luatexja` has nothing to set.
          fontspec
          luatexja
          haranoaji

          # Structure the recovered document actually uses: tables with the
          # document's own rules, listings for fixed-pitch blocks, hyperref for
          # the links and destinations the backend already records.
          booktabs
          multirow
          tools          # array, longtable, multicol
          listings
          fancyvrb
          # `fancyvrb` here is still the 2.8 line, which has no `breaklines`
          # at all — `\fvset{breaklines=true}` is a fatal xkeyval error, not a
          # silent no-op. `fvextra` is the package that adds it (and
          # `breakanywhere`, which is what a code listing with no spaces in
          # its long lines actually needs). `--format latex` wraps every code
          # block in a `Verbatim`, so without this every over-long listing
          # line runs off the page.
          fvextra
          hyperref
          caption
          geometry
          xcolor
          ulem

          # Drawings. The elements are already vector paths, so TikZ can draw
          # them directly rather than the figure being dropped or rasterised.
          pgf
        ]);

      # ── the home-manager module ────────────────────────────────────────────
      homeModule = { config, lib, pkgs, ... }:
        let
          cfg = config.programs.rustyfi;
          tomlFormat = pkgs.formats.toml { };
        in
        {
          options.programs.rustyfi = {
            enable = lib.mkEnableOption "rustyfi, a Rust port of the SATySFi typesetter";

            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.stdenv.hostPlatform.system}.rustyfi;
              defaultText = lib.literalExpression "rustyfi.packages.\${system}.rustyfi";
              description = "The rustyfi package to install.";
            };

            settings = lib.mkOption {
              inherit (tomlFormat) type;
              default = { };
              example = lib.literalExpression ''
                { registry.url = "https://github.com/na4zagin3/satyrographos-repo.git"; }
              '';
              description = ''
                Written to {file}`$XDG_CONFIG_HOME/rustyfi/config.toml`. This
                shadows the copy shipped inside the package entirely, rather
                than merging with it — see the comments in the shipped
                {file}`config.toml`.
              '';
            };

            fontsDir = lib.mkOption {
              type = lib.types.nullOr lib.types.path;
              default = null;
              example = lib.literalExpression ''"''${config.home.homeDirectory}/.local/share/rustyfi-fonts"'';
              description = ''
                A font ROOT, exported as {env}`RUSTYFI_FONT_DIR`. It uses the
                same layout convention as the library root: the faces under
                {file}`dist/fonts/` and their index at
                {file}`dist/hash/fonts.satysfi-hash`.

                The package ships no faces — the ones
                {file}`download-fonts.sh` fetches are gitignored and so are not
                part of the flake source. Without this, text is set in the
                built-in base-14 fonts, which is enough for Latin-only
                documents but not for the bundled CJK or math packages.
              '';
            };
          };

          config = lib.mkIf cfg.enable {
            home.packages = [ cfg.package ];

            xdg.configFile."rustyfi/config.toml" = lib.mkIf (cfg.settings != { }) {
              source = tomlFormat.generate "rustyfi-config.toml" cfg.settings;
            };

            home.sessionVariables = lib.mkIf (cfg.fontsDir != null) {
              RUSTYFI_FONT_DIR = toString cfg.fontsDir;
            };
          };
        };
    in
    flake-utils.lib.eachDefaultSystem
      (system:
        let
          pkgs = import nixpkgs { inherit system; };
          rustyfi = mkRustyfi pkgs;
          # The reference typesetter the port is compared against.
          satysfi = pkgs.satysfi;
          tex = texForRustyfi pkgs;
        in
        {
          packages = {
            inherit rustyfi satysfi tex;
            default = rustyfi;
          };

          apps.rustyfi = {
            type = "app";
            program = "${rustyfi}/bin/rustyfi";
          };
          apps.satysfi = {
            type = "app";
            program = "${satysfi}/bin/satysfi";
          };
          apps.default = self.apps.${system}.rustyfi;

          checks.rustyfi = rustyfi;

          devShells.default = pkgs.mkShell {
            inputsFrom = [ rustyfi ];
            packages = [
              pkgs.cargo
              pkgs.rustc
              pkgs.clippy
              pkgs.rustfmt
              satysfi                 # the reference typesetter (0.0.11)
              pkgs.satyrographos      # its package manager
              pkgs.poppler-utils      # pdftotext / pdfinfo — layout extraction
              pkgs.python3            # layout-tests/fidelity.py, benchmark.py
              tex                     # `--format latex` output, actually compiled
            ];
            shellHook = ''
              echo "rustyfi dev shell — SATySFi $(satysfi --version 2>/dev/null \
                | grep -oE '[0-9.]+' | head -1) available as the comparison target"
              echo "  layout fidelity:  python3 layout-tests/fidelity.py"
              echo "  benchmark:        python3 benchmark.py --satysfi \$(command -v satysfi)"
              echo "  latex round-trip: rustyfi --format latex doc.saty -o doc.tex \\"
              echo "                    && lualatex doc.tex     # xelatex/pdflatex also present"
            '';
          };
        })
    // {
      # System-independent outputs.
      homeManagerModules.rustyfi = homeModule;
      homeManagerModules.default = homeModule;

      overlays.default = final: _prev: { rustyfi = mkRustyfi final; };
    };
}
