use crate::span::Span;
use syan::TokenLeaves;

/// One SATySFi token. Variant names and payloads mirror the token declarations
/// of the v0.0.6 `parser.mly` (`LETNONREC` = `Let`, `LAMBDA` = `Fun`, ...).
/// Command payloads keep their sigil, exactly like the OCaml lexer
/// (`HorzCmd("\\emph")`, `VertCmd("+p")`).
///
/// The `#[leaf(...)]`-annotated variants get a matching leaf struct
/// (`KwLet`, `VarTok`, ...) generated by `#[derive(TokenLeaves)]`, with the
/// same peek → match → push-back-on-mismatch `Parse`/`Unparse`/`Spanned` the
/// old `unit_tokens!`/`payload_tokens!` macros produced. Multi-field and
/// multi-variant-matching leaves (`LengthTok`, `LiteralTok`, `BinOpTok`,
/// `VarInHorzTok`, ...) stay hand-written in [`crate::leaf`].
#[derive(Clone, Debug, PartialEq, TokenLeaves)]
#[token_leaf(atom = "Atom", span = "|a| a.span")]
pub enum Token {
    // ---- headers ----
    #[leaf(name = "HeaderRequireTok", expect = "'@require:'", field = "content")]
    HeaderRequire(String),
    #[leaf(name = "HeaderImportTok", expect = "'@import:'", field = "content")]
    HeaderImport(String),
    HeaderStage0,
    HeaderStage1,
    HeaderPersistent0,

    // ---- identifiers & constants (program mode) ----
    #[leaf(name = "VarTok", expect = "a variable name", field = "name")]
    Var(String),
    VarWithMod(Vec<String>, String),
    #[leaf(name = "CtorTok", expect = "a constructor name", field = "name")]
    Constructor(String),
    #[leaf(name = "TypeVarTok", expect = "a type variable", field = "name")]
    TypeVar(String),
    #[leaf(name = "OpenModuleTok", expect = "'Mod.('", field = "name")]
    OpenModule(String), // `Mod.(`
    /// `M.N.P` — a dotted module path ending in an UPPER segment
    /// (upstream `LONG_UPPER`, `lexer_v1.mll:357-363`). SATySFi 0.1-only:
    /// under 0.0.6 this spelling is a lex error ("module path must end
    /// with a variable name"), unchanged. Payload mirrors
    /// [`Token::VarWithMod`]: `mods = ["M","N"]`, final segment `"P"` —
    /// upstream's `(modidents, modident0)` pair carries the same split
    /// (`parser_v1.mly:407-413` reassembles the chain from it).
    LongUpper(Vec<String>, String),
    #[leaf(name = "IntTok", expect = "an integer constant", field = "value")]
    IntConst(i64),
    #[leaf(name = "FloatTok", expect = "a float constant", field = "value")]
    FloatConst(f64),
    LengthConst(f64, String),
    /// Backtick string literal. `omit_pre`/`omit_post` mirror the OCaml
    /// `LITERAL(_, s, pre, post)` flags (whether an adjacent space is trimmed).
    Literal {
        body: String,
        omit_pre: bool,
        omit_post: bool,
    },

    // ---- keywords ----
    //
    // NOTE: `not` used to have its own reserved `Not` keyword token here,
    // with no grammar rule anywhere ever consuming it (`AppExpr`'s doc
    // comment used to list `not` among the unimplemented unary forms) —
    // meaning the surface grammar could never actually reference the
    // registered `"not"` primitive (`primitives.rs`), even though it
    // type-checked and evaluated fine when built by hand
    // (`eval_phase2.rs`'s `not`-applying test constructs the `Ast` directly,
    // skipping the parser). Tier-2 decoration/graphics packages
    // (`picture.satyh`'s `not (x1r >' x2r)`/`not reversed`,
    // docs/plans/stdlib-port.md) are the first bundled source to actually
    // call `not` from real syntax, which is what surfaced this: removing
    // the special-case keyword mapping (`lexer.rs`'s `keyword`) lets `not`
    // lex as an ordinary `Var`/`VarTok`, exactly like any other primitive
    // name (`arabic`, `floor`, ...) — an ordinary application `not expr`
    // (or `not (expr)`) then just works through the existing `AppExpr`
    // machinery, no new grammar rule needed.
    Mod,
    #[leaf(name = "KwIf", expect = "'if'")]
    If,
    #[leaf(name = "KwThen", expect = "'then'")]
    Then,
    #[leaf(name = "KwElse", expect = "'else'")]
    Else,
    #[leaf(name = "KwLet", expect = "'let'")]
    Let, // `let` (LETNONREC)
    #[leaf(name = "KwLetRec", expect = "'let-rec'")]
    LetRec, // `let-rec`
    #[leaf(name = "KwAnd", expect = "'and'")]
    LetAnd, // `and`
    #[leaf(name = "KwIn", expect = "'in'")]
    In,
    #[leaf(name = "KwFun", expect = "'fun'")]
    Fun, // `fun` (LAMBDA)
    #[leaf(name = "KwTrue", expect = "'true'")]
    True,
    #[leaf(name = "KwFalse", expect = "'false'")]
    False,
    #[leaf(name = "KwBefore", expect = "'before'")]
    Before,
    #[leaf(name = "KwWhile", expect = "'while'")]
    While,
    #[leaf(name = "KwDo", expect = "'do'")]
    Do,
    #[leaf(name = "KwLetMutable", expect = "'let-mutable'")]
    LetMutable, // `let-mutable`
    #[leaf(name = "KwMatch", expect = "'match'")]
    Match,
    #[leaf(name = "KwWith", expect = "'with'")]
    With,
    #[leaf(name = "KwWhen", expect = "'when'")]
    When,
    #[leaf(name = "KwAs", expect = "'as'")]
    As,
    #[leaf(name = "KwType", expect = "'type'")]
    Type,
    #[leaf(name = "KwOf", expect = "'of'")]
    Of,
    #[leaf(name = "KwModule", expect = "'module'")]
    Module,
    #[leaf(name = "KwStruct", expect = "'struct'")]
    Struct,
    #[leaf(name = "KwSig", expect = "'sig'")]
    Sig,
    #[leaf(name = "KwVal", expect = "'val'")]
    Val,
    #[leaf(name = "KwEnd", expect = "'end'")]
    End,
    #[leaf(name = "KwDirect", expect = "'direct'")]
    Direct,
    #[leaf(name = "ConstraintTok", expect = "'constraint'")]
    Constraint,
    #[leaf(name = "KwLetHorz", expect = "'let-inline'")]
    LetHorz, // `let-inline`
    #[leaf(name = "KwLetVert", expect = "'let-block'")]
    LetVert, // `let-block`
    #[leaf(name = "KwLetMath", expect = "'let-math'")]
    LetMath, // `let-math`
    Controls,
    Cycle,
    #[leaf(name = "HorzCmdTypeTok", expect = "'inline-cmd'")]
    HorzCmdType, // `inline-cmd`
    #[leaf(name = "VertCmdTypeTok", expect = "'block-cmd'")]
    VertCmdType, // `block-cmd`
    #[leaf(name = "MathCmdTypeTok", expect = "'math-cmd'")]
    MathCmdType, // `math-cmd`
    #[leaf(name = "CommandTok", expect = "'command'")]
    Command,
    #[leaf(name = "KwOpen", expect = "'open'")]
    Open,
    /// `rec` — SATySFi 0.1-only keyword (`val rec`/`let rec`); under 0.0.6
    /// this word stays a plain identifier (see `lexer.rs`'s version-gated
    /// keyword table).
    #[leaf(name = "KwRec", expect = "'rec'")]
    Rec,
    /// `inline` — SATySFi 0.1-only keyword (`val inline \cmd = ...`).
    #[leaf(name = "KwInline", expect = "'inline'")]
    Inline,
    /// `block` — SATySFi 0.1-only keyword (`val block +cmd = ...`).
    #[leaf(name = "KwBlock", expect = "'block'")]
    Block,
    /// `mutable` — SATySFi 0.1-only keyword (`val mutable x <- e`/`let
    /// mutable x <- e in ..`); under 0.0.6 this word stays a plain
    /// identifier (see `lexer.rs`'s version-gated keyword table).
    #[leaf(name = "KwMutable", expect = "'mutable'")]
    Mutable,
    /// `signature` — SATySFi 0.1-only keyword (`signature S = sig … end`,
    /// upstream `lexer_v1.mll:348`); a plain identifier under 0.0.6.
    #[leaf(name = "KwSignature", expect = "'signature'")]
    Signature,
    /// `include` — SATySFi 0.1-only keyword (`include M` binds /
    /// `include S` decls, `lexer_v1.mll:335`); a plain identifier under
    /// 0.0.6.
    #[leaf(name = "KwInclude", expect = "'include'")]
    Include,
    /// `use` — SATySFi 0.1-only keyword (Envelopes packaging headers `use
    /// package …` / `use … of `<path>``, `saphe-split:parser.mly:371-380 @
    /// b836d512`); a plain identifier under 0.0.6 (no 0.0.6 grammar reserves
    /// it — see `lexer.rs`'s version-gated keyword table).
    #[leaf(name = "KwUse", expect = "'use'")]
    Use,
    /// `package` — SATySFi 0.1-only keyword (`use package …`); a plain
    /// identifier under 0.0.6.
    #[leaf(name = "KwPackage", expect = "'package'")]
    Package,
    /// `math` — SATySFi 0.1-only keyword (`val math <ctx> \cmd … = …`,
    /// `parser_v1.mly:452-453` dispatch, MATH reserved at :240); a plain
    /// identifier under 0.0.6 (0.0.6 has no `math` keyword — the word
    /// survives only as the surface name of `BaseType::MathText`,
    /// `math-split` spec §1.1).
    #[leaf(name = "KwMath", expect = "'math'")]
    Math,

    // ---- grouping delimiters ----
    #[leaf(name = "LParenTok", expect = "'('")]
    LParen,
    #[leaf(name = "RParenTok", expect = "')'")]
    RParen,
    #[leaf(name = "BRecordTok", expect = "'(|'")]
    BRecord, // `(|`
    #[leaf(name = "ERecordTok", expect = "'|)'")]
    ERecord, // `|)`
    #[leaf(name = "BListTok", expect = "'['")]
    BList, // `[`
    #[leaf(name = "EListTok", expect = "']'")]
    EList, // `]`
    #[leaf(name = "BHorzGrpTok", expect = "'{'")]
    BHorzGrp, // `{` opening inline text
    #[leaf(name = "EHorzGrpTok", expect = "'}'")]
    EHorzGrp, // `}` closing inline text
    #[leaf(name = "BVertGrpTok", expect = "'<'")]
    BVertGrp, // `'<` / `<` opening block text
    #[leaf(name = "EVertGrpTok", expect = "'>'")]
    EVertGrp, // `>` closing block text
    #[leaf(name = "BMathGrpTok", expect = "'${'")]
    BMathGrp, // `${` / `{` opening math
    #[leaf(name = "EMathGrpTok", expect = "'}'")]
    EMathGrp, // `}` closing math
    BPath, // `<[`
    EPath, // `]>`

    // ---- punctuation & operators (program mode) ----
    #[leaf(name = "ListPunctTok", expect = "';'")]
    ListPunct, // `;`
    #[leaf(name = "AccessTok", expect = "'#'")]
    Access, // `#`
    #[leaf(name = "ArrowTok", expect = "'->'")]
    Arrow, // `->`
    #[leaf(name = "OverwriteEqTok", expect = "'<-'")]
    OverwriteEq, // `<-`
    #[leaf(name = "BarTok", expect = "'|'")]
    Bar, // `|`
    #[leaf(name = "WildcardTok", expect = "'_'")]
    Wildcard, // `_`
    #[leaf(name = "ColonTok", expect = "':'")]
    Colon,
    #[leaf(name = "CommaTok", expect = "','")]
    Comma,
    #[leaf(name = "ConsTok", expect = "'::'")]
    Cons, // `::`
    /// `:>` — signature coercion/ascription (COERCE, `lexer_v1.mll:280`).
    /// SATySFi 0.1-only: under 0.0.6 the same two characters lex as
    /// `Colon` + `BinopGt(">")`, unchanged.
    #[leaf(name = "CoerceTok", expect = "':>'")]
    Coerce,
    #[leaf(name = "ExactMinusTok", expect = "'-'")]
    ExactMinus,
    #[leaf(name = "DefEqTok", expect = "'='")]
    DefEq, // `=`
    #[leaf(name = "ExactTimesTok", expect = "'*'")]
    ExactTimes, // `*`
    ExactAmp,   // `&`
    ExactTilde, // `~`
    PathCurve,  // `..`
    PathLine,   // `--`
    BinopPlus(String),
    BinopMinus(String),
    BinopTimes(String),
    BinopDivides(String),
    BinopEq(String),
    BinopLt(String),
    BinopGt(String),
    BinopAmp(String),
    BinopBar(String),
    BinopHat(String),
    #[leaf(name = "UnopExclamTok", expect = "a '!' operator", field = "text")]
    UnopExclam(String),
    #[leaf(name = "OptionalTypeTok", expect = "'?'")]
    OptionalType, // `?`
    #[leaf(name = "OptionalArrowTok", expect = "'?->'")]
    OptionalArrow, // `?->`
    #[leaf(name = "OptionalTok", expect = "'?:'")]
    Optional, // `?:`
    #[leaf(name = "OmissionTok", expect = "'?*'")]
    Omission, // `?*`
    /// `?'r` — a SATySFi 0.1 row variable (upstream `ROWVAR`,
    /// `lexer_v1.mll:310-311`; "optional-arg-rows increment 2"). `RowVarTok`
    /// carries the name sans sigil, exactly like [`Token::TypeVar`]/
    /// `TypeVarTok`. V0_1-only: the lexer (`lexer.rs`'s `'?'` arm) only ever
    /// mints this under `SatysfiVersion::V0_1`; under `V0_0_6`, `?'r` stays
    /// two tokens (`OptionalType` then `TypeVar`), byte-identical to before
    /// this addition.
    #[leaf(name = "RowVarTok", expect = "a row variable (\"?'r\")", field = "name")]
    RowVar(String), // `?'r`

    // ---- commands (payload includes the `\`/`+` sigil) ----
    #[leaf(name = "HorzCmdTok", expect = "an inline command", field = "name")]
    HorzCmd(String),
    HorzCmdWithMod(Vec<String>, String),
    HorzMacro(String),
    #[leaf(name = "VertCmdTok", expect = "a block command", field = "name")]
    VertCmd(String),
    VertCmdWithMod(Vec<String>, String),
    VertMacro(String),
    #[leaf(name = "MathCmdTok", expect = "a math command", field = "name")]
    MathCmd(String),
    MathCmdWithMod(Vec<String>, String),

    // ---- text-mode content ----
    VarInHorz(Vec<String>, String),
    VarInVert(Vec<String>, String),
    VarInMath(Vec<String>, String),
    #[leaf(name = "CharTok", expect = "inline text", field = "text")]
    Char(String),
    #[leaf(name = "SpaceTok", expect = "a space")]
    Space,
    #[leaf(name = "BreakTok", expect = "a line break")]
    Break,
    #[leaf(name = "ItemTok", expect = "an itemize bullet", field = "depth")]
    Item(usize), // `*`+ with depth
    #[leaf(name = "SepTok", expect = "'|' separator")]
    Sep, // `|`
    #[leaf(name = "EndActiveTok", expect = "';'")]
    EndActive, // `;` closing an active area

    // ---- math-mode content ----
    #[leaf(name = "MathCharTok", expect = "a math character", field = "text")]
    MathChar(String),
    #[leaf(name = "SuperscriptTok", expect = "'^'")]
    Superscript, // `^`
    #[leaf(name = "SubscriptTok", expect = "'_'")]
    Subscript, // `_`
    #[leaf(name = "PrimesTok", expect = "a primes mark", field = "count")]
    Primes(usize),

    #[leaf(name = "EoiTok", expect = "end of input")]
    Eoi,
}

impl std::fmt::Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use Token::*;
        match self {
            HeaderRequire(s) => write!(f, "@require: {s}"),
            HeaderImport(s) => write!(f, "@import: {s}"),
            HeaderStage0 => write!(f, "@stage: 0"),
            HeaderStage1 => write!(f, "@stage: 1"),
            HeaderPersistent0 => write!(f, "@stage: persistent"),
            Var(s) | Constructor(s) => write!(f, "{s}"),
            VarWithMod(m, s) | LongUpper(m, s) => write!(f, "{}.{s}", m.join(".")),
            TypeVar(s) => write!(f, "'{s}"),
            OpenModule(s) => write!(f, "{s}.("),
            IntConst(n) => write!(f, "{n}"),
            FloatConst(x) => write!(f, "{x}"),
            LengthConst(x, u) => write!(f, "{x}{u}"),
            Literal { body, .. } => write!(f, "`{body}`"),
            Mod => write!(f, "mod"),
            If => write!(f, "if"),
            Then => write!(f, "then"),
            Else => write!(f, "else"),
            Let => write!(f, "let"),
            LetRec => write!(f, "let-rec"),
            LetAnd => write!(f, "and"),
            In => write!(f, "in"),
            Fun => write!(f, "fun"),
            True => write!(f, "true"),
            False => write!(f, "false"),
            Before => write!(f, "before"),
            While => write!(f, "while"),
            Do => write!(f, "do"),
            LetMutable => write!(f, "let-mutable"),
            Match => write!(f, "match"),
            With => write!(f, "with"),
            When => write!(f, "when"),
            As => write!(f, "as"),
            Type => write!(f, "type"),
            Of => write!(f, "of"),
            Module => write!(f, "module"),
            Struct => write!(f, "struct"),
            Sig => write!(f, "sig"),
            Val => write!(f, "val"),
            End => write!(f, "end"),
            Direct => write!(f, "direct"),
            Constraint => write!(f, "constraint"),
            LetHorz => write!(f, "let-inline"),
            LetVert => write!(f, "let-block"),
            LetMath => write!(f, "let-math"),
            Controls => write!(f, "controls"),
            Cycle => write!(f, "cycle"),
            HorzCmdType => write!(f, "inline-cmd"),
            VertCmdType => write!(f, "block-cmd"),
            MathCmdType => write!(f, "math-cmd"),
            Command => write!(f, "command"),
            Open => write!(f, "open"),
            Rec => write!(f, "rec"),
            Inline => write!(f, "inline"),
            Block => write!(f, "block"),
            Mutable => write!(f, "mutable"),
            Signature => write!(f, "signature"),
            Include => write!(f, "include"),
            Use => write!(f, "use"),
            Package => write!(f, "package"),
            Math => write!(f, "math"),
            LParen => write!(f, "("),
            RParen => write!(f, ")"),
            BRecord => write!(f, "(|"),
            ERecord => write!(f, "|)"),
            BList => write!(f, "["),
            EList => write!(f, "]"),
            BHorzGrp => write!(f, "{{"),
            EHorzGrp => write!(f, "}}"),
            BVertGrp => write!(f, "'<"),
            EVertGrp => write!(f, ">"),
            BMathGrp => write!(f, "${{"),
            EMathGrp => write!(f, "}}"),
            BPath => write!(f, "<["),
            EPath => write!(f, "]>"),
            ListPunct => write!(f, ";"),
            Access => write!(f, "#"),
            Arrow => write!(f, "->"),
            OverwriteEq => write!(f, "<-"),
            Bar => write!(f, "|"),
            Wildcard => write!(f, "_"),
            Colon => write!(f, ":"),
            Comma => write!(f, ","),
            Cons => write!(f, "::"),
            Coerce => write!(f, ":>"),
            ExactMinus => write!(f, "-"),
            DefEq => write!(f, "="),
            ExactTimes => write!(f, "*"),
            ExactAmp => write!(f, "&"),
            ExactTilde => write!(f, "~"),
            PathCurve => write!(f, ".."),
            PathLine => write!(f, "--"),
            BinopPlus(s) | BinopMinus(s) | BinopTimes(s) | BinopDivides(s) | BinopEq(s)
            | BinopLt(s) | BinopGt(s) | BinopAmp(s) | BinopBar(s) | BinopHat(s)
            | UnopExclam(s) => write!(f, "{s}"),
            OptionalType => write!(f, "?"),
            OptionalArrow => write!(f, "?->"),
            Optional => write!(f, "?:"),
            Omission => write!(f, "?*"),
            RowVar(s) => write!(f, "?'{s}"),
            HorzCmd(s) | VertCmd(s) | MathCmd(s) | HorzMacro(s) | VertMacro(s) => {
                write!(f, "{s}")
            }
            HorzCmdWithMod(m, s) | VertCmdWithMod(m, s) | MathCmdWithMod(m, s) => {
                let (sigil, name) = s.split_at(1);
                write!(f, "{sigil}{}.{name}", m.join("."))
            }
            VarInHorz(m, s) | VarInVert(m, s) | VarInMath(m, s) => {
                if m.is_empty() {
                    write!(f, "#{s}")
                } else {
                    write!(f, "#{}.{s}", m.join("."))
                }
            }
            Char(s) => write!(f, "{s}"),
            Space => write!(f, " "),
            Break => writeln!(f),
            Item(n) => write!(f, "{}", "*".repeat(*n)),
            Sep => write!(f, "|"),
            EndActive => write!(f, ";"),
            MathChar(s) => write!(f, "{s}"),
            Superscript => write!(f, "^"),
            Subscript => write!(f, "_"),
            Primes(n) => write!(f, "{}", "'".repeat(*n)),
            Eoi => Ok(()),
        }
    }
}

/// A token together with its source span: the atom type fed to the syan parser.
pub type Atom = syan::span::WithSpan<Token, Span>;
